#!/bin/bash

cwd=`pwd`

cd "/afs/cern.ch/work/j/jkaspar/work/software/ctpps/production/CMSSW_12_1_0_pre3"

if [ -f "environment" ]
then
	source environment
else
	source /cvmfs/cms.cern.ch/cmsset_default.sh
	cd src
	eval `scramv1 runtime -sh`
fi

export CMSSW_SEARCH_PATH="$CMSSW_SEARCH_PATH:$cwd"

cd "$cwd"

echo "CMSSW_BASE=$CMSSW_BASE"
