#!/bin/bash

periods=(
	"2016_preTS2"
	"2017_preTS2"
	"2017_postTS2"
	"2018"
)

#----------------------------------------------------------------------------------------------------

function Run()
{
	version="$1"

	for period in ${periods[*]}
	do
		dir="data/$version/$period/"

		mkdir -p "$dir"
		cp -R templates/* "$dir"
		cp settings/$period/* "$dir"

		cd "$dir" || exit

		cwd=`pwd -P`
		cwd=${cwd#*proton_simulation_validation/}

		sed -i "s|\$CWD|$cwd|" direct_simu_reco_cff.py

		rm -f *.root
		rm -f *.log

		./run_all "$version/$period" &

		cd - > /dev/null
	done
}

#----------------------------------------------------------------------------------------------------

#Run "version1"

#Run "version2"

# SW: /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src at 765fc41562f365c3f9d200724d6aabbfa15d3838
#Run "version3"

Run "version4-test"
