#!/bin/bash

periods=(
	"2016_preTS2"
	"2016_postTS2"

	"2017_preTS2"
	"2017_postTS2"

	"2018_preTS1"
	"2018_TS1_TS2"
	"2018_postTS2"

	"2021"
)

#----------------------------------------------------------------------------------------------------

function Run()
{
	echo "* $version"

	# make version directory
	mkdir -p "data/$version"

	# initiate submission script
	condor_file_sub="data/$version/condor.sub"

	(
		local base_dir_full="$(pwd)"
		echo "executable = $base_dir_full/\$(dir)/job"
		echo "arguments = \$(ClusterId) \$(ProcId) \\\"\$(dir)\\\""
		echo "output = $base_dir_full/\$(dir)/out"
		echo "error = $base_dir_full/\$(dir)/err"
		echo "log = $base_dir_full/condor_${selection}.log"

		echo "+MaxRuntime = 3600"
		#echo "+JobBatchName = \"$job_name\""
		#echo "requirements = (OpSysAndVer =?= \"SLCern6\")"
		echo "requirements = (OpSysAndVer =?= \"CentOS7\")"

	) > "$condor_file_sub"

	# submit each period
	for period in ${periods[*]}
	do
		echo " - $period"

		dir="data/$version/$period"
		full_dir="$(pwd -P)/data/$version/$period"

		# make and clean directory
		mkdir -p "$dir"
		cp -R templates/* "$dir"
		cp settings/$period/* "$dir"

		rm -f $dir/*.root
		rm -f $dir/*.log

		# make job script
		cat "template_job" | sed "\
				s|\$sw_dir|$CMSSW_BASE|g;\
				s|\$job_dir|$full_dir|g;\
				s|\$version|$version|g;\
				s|\$period|$period|g;\
			" > "$dir/job"

		chmod u+x "$dir/job"

		# add submission line
		(
			echo ""
			echo "dir=$dir"
			echo "queue"
		) >> "$condor_file_sub"
	done

	# submit
	echo "In order to submit do:"
	echo "    condor_submit \"$condor_file_sub"\"
}

#----------------------------------------------------------------------------------------------------

make || exit 1

#----------------------------------------------------------------------------------------------------

#Run "version1"

#Run "version2"

# SW: /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/proton_reco_step4/CMSSW_10_6_1/src at 765fc41562f365c3f9d200724d6aabbfa15d3838
#Run "version3"

#Run "version4-test"

# CMSSW: at 4938224d8255bcdda59ce09816fa4d6f7510f399
# this repo: at 251c2741484148fadd97a8c11a2d76a6bfedea6c
#Run "version5"

# CMSSW: at 1ebb05f3c961cde76c7386effb43b4de5a0ee5b3
# this repo: at 87beb45e80d58b95afe7e1c4190d3c428351b738
#Run "version6"

# /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/pps_validation_update/CMSSW_11_0_0_pre12
#   at afad251d1329c5225c10c2f8171049c51f576c7a
# this repo: at f2d2117a4817cd6306a9fc0d12acbab1f8d5b157
#Run "version7"

# /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/pps_address_comments/CMSSW_11_1_X_2019-12-12-1100
#   at TODO
# this repo: at TODO
#Run "version8"

# /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/pps_backport_10_6/CMSSW_10_6_8
#   at 7f4177b1ff65c5dde48181abdc8f77c31ccea46a
# this repo: at f3925cb873f37b1f8e6ad6b6ee693a6be0ccb6af
#Run "version9"

version="version10"
# /afs/cern.ch/work/j/jkaspar/work/software/ctpps/development/pps_direct_simu_update/CMSSW_11_1_0_pre7
#   at 18bdbf1b7ce
# this repo: at TODO
Run
