#!/bin/bash

echo "* running: $1"

#----------------------------------------------------------------------------------------------------

for tag in test_*
do
	tag=${tag%_cfg*}

	cmsRun "${tag}_cfg.py" &> "${tag}.log" &
done

#----------------------------------------------------------------------------------------------------

stat="1E5"

cd "proton_reco_resolution"
./run_multiple "$stat"
cd - > /dev/null

cd "proton_reco_misalignment"
./run_multiple "$stat"
cd - > /dev/null

cd "proton_reco_optics"
./run_multiple "$stat"
cd - > /dev/null

cd "proton_reco_efficiency"
./run_multiple "$stat"
cd - > /dev/null

#----------------------------------------------------------------------------------------------------

wait

echo "* done: $1"
