#!/bin/bash

version="$1"
period="$2"

label="$1/$2"

echo "* running: $label"

#----------------------------------------------------------------------------------------------------

for tag in test_*.py
do
	tag=${tag%_cfg*}

	cmsRun "${tag}_cfg.py" &> "${tag}.log" &
done

#----------------------------------------------------------------------------------------------------

# TODO to 4E5
stat="4E6"

cd "proton_reco_resolution"
./run_multiple "$stat"
cd - > /dev/null

cd "proton_reco_misalignment"
./run_multiple "$stat"
cd - > /dev/null

cd "proton_reco_optics"
./run_multiple "$stat"
cd - > /dev/null

# this shall stay commented out
#cd "proton_reco_efficiency"
#./run_multiple "$stat"
#cd - > /dev/null

#----------------------------------------------------------------------------------------------------

wait

# cumulative processing
../../../collect_systematics "$period" &> collect_systematics.log

echo "* done: $label"
