#!/bin/bash

for tag in test_acceptance test_beam_smearing test_proton_gun test_smearing_effects test_xy_pattern
do
	cmsRun "${tag}_cfg.py" &> "${tag}.log" &
done

./resolution_run_multiple "100" "1E3"
./misalignment_run_multiple "100" "1E3"
